### ISSUE TITLE
Combining fastq and fast5 fails with a read not found error.

### ISSUE THREAD

**Issue by mattloose** [AlexanderVi/ont2cram#9] opened 2019-10-03 15:51 UTC
When providing fast5 and fastq files together, ont2cram fails by being unable to locate a read.

I will send example files.

**Comment by AlexanderVi** [comment] 2019-10-04 11:38
Please provide exact command line. Thanks

**Comment by mattloose** [comment] 2019-10-04 11:43
Sure - it's below. I've redacted some info from the full path. This also fails on the pass folder.

These are the same files you have.

`
ont2cram -i 20190822_0714_GA30000_FAL00432_91168a14/fast5_fail/ -f 20190822_0714_GA30000_FAL00432_91168a14/fastq_fail/ -o FAIL_plus_seq
Loading FASTQ from: '/##/##/##/20190822_0714_GA30000_FAL00432_91168a14/fastq_fail'
100%|████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 10.31it/s]
Loading Fast5 from: '/##/##/##/20190822_0714_GA30000_FAL00432_91168a14/fast5_fail'
100%|████████████████████████████████████████████████████████████████| 2/2 [00:14<00:00,  7.37s/it]
Writing CRAM to: '/##/##/##/FAIL_plus_seq'
  0%|                                                                        | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mattloose/software/GIT/ont2cram/env/bin/ont2cram", line 4, in <module>
    __import__('pkg_resources').run_script('ont2cram==0.0.1', 'ont2cram')
  File "/Users/mattloose/software/GIT/ont2cram/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mattloose/software/GIT/ont2cram/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1451, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/mattloose/software/GIT/ont2cram/env/lib/python3.6/site-packages/ont2cram-0.0.1-py3.6.egg/EGG-INFO/scripts/ont2cram", line 5, in <module>
  File "/Users/mattloose/software/GIT/ont2cram/env/lib/python3.6/site-packages/ont2cram-0.0.1-py3.6.egg/ont2cram.py", line 380, in main
  File "/Users/mattloose/software/GIT/ont2cram/env/lib/python3.6/site-packages/ont2cram-0.0.1-py3.6.egg/ont2cram.py", line 367, in run
  File "/Users/mattloose/software/GIT/ont2cram/env/lib/python3.6/site-packages/ont2cram-0.0.1-py3.6.egg/ont2cram.py", line 325, in write_cram
KeyError: b'001e76f2-a832-4743-b3d3-6de5461a6f44'`

**Comment by AlexanderVi** [comment] 2019-11-21 06:32
This is a bug caused by using different type for dict keys ( str vs bytes ) - fix coming soon

**Comment by AlexanderVi** [comment] 2019-12-03 22:40
This has been fixed in de25e3d ( line 347 )

**Closed as completed by AlexanderVi** 2019-12-03 22:40 UTC
